
import java.applet.*; 
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.net.*; 
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramdhan
 */
public class formUtama extends javax.swing.JFrame {
    MinHeap heap = new MinHeap(999);
    private String kode;
    //Terbilang terbilang = new Terbilang();
    public String getKode() {
        return kode;
    }

    public void setKode(String kode) {
        this.kode = kode;
    }
    
    /**
     * Creates new form formUtama
     */
    public formUtama() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtMeja1 = new javax.swing.JTextField();
        txtMeja2 = new javax.swing.JTextField();
        btnMeja2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPersonal = new javax.swing.JButton();
        btnBisnis = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Antrian Prioritas");
        setResizable(false);

        jButton1.setText("Panggil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnMeja2.setText("Panggil");
        btnMeja2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeja2ActionPerformed(evt);
            }
        });

        jLabel1.setText("MEJA 1");

        jLabel2.setText("MEJA 2");

        btnPersonal.setText("AMBIL ANTRIAN PERSONAL");
        btnPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalActionPerformed(evt);
            }
        });

        btnBisnis.setText("AMBIL ANTRIAN BISNIS");
        btnBisnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBisnisActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo - Copy.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("orange juice", 0, 14)); // NOI18N
        jLabel5.setText("Antrian Bank PT.Bank Jaya UNIKOM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(132, 132, 132))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnBisnis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                        .addComponent(txtMeja1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnMeja2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                        .addComponent(txtMeja2))))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(83, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMeja1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(txtMeja2))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnMeja2))
                .addGap(18, 18, 18)
                .addComponent(btnPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBisnis, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(heap.getHeapSize()==0){
           txtMeja1.setText("");
           //tambahkan modal dialog 
           System.out.println("ANTRIAN KOSONG");
           
           JOptionPane.showMessageDialog(rootPane, "ANTRIAN KOSONG");
            
        }else {
            kode = heap.getMin(); 
            txtMeja1.setText(kode);
            URL fileurut = formUtama.class.getResource("sound/nomor-urut.wav");
            PlaySound(fileurut);
            
            char[] putar =kode.toCharArray();
            int i = 0;
            while(i<putar.length){
                try{
                    URL file = formUtama.class.getResource("sound/"+putar[i]+".wav");
                    PlaySound(file);
                    i++;
                }catch(Exception e){
                   e.printStackTrace();
                }
            }
           URL kemeja = formUtama.class.getResource("sound/loket.wav");
           PlaySound(kemeja);
           
           URL satu1 = formUtama.class.getResource("sound/1.wav");
           PlaySound(satu1);
            
        }
        
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalActionPerformed
        // TODO add your handling code here:
        if(heap.getHeapSize()==0){
            kode = "P001";
            heap.insert(kode);
        }else {
            int now  = heap.getHeapSize()+1;
            System.out.println(now);
            kode = "P"+String.format("%03d", now);
            heap.insert(kode);
        }
            helper.kode = kode;
            new formAntrian().setVisible(true);
    }//GEN-LAST:event_btnPersonalActionPerformed

    private void btnBisnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBisnisActionPerformed
        // TODO add your handling code here:
        if(heap.getHeapSize()==0){
            kode = "B001";
            heap.insert(kode);
        }else {
            int now  = heap.getHeapSize()+1;
            System.out.println(now);
            kode = "B"+String.format("%03d", now);
            heap.insert(kode);
        }
            helper.kode = kode;
            new formAntrian().setVisible(true);
    }//GEN-LAST:event_btnBisnisActionPerformed

    private void btnMeja2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeja2ActionPerformed
        // TODO add your handling code here:
        if(heap.getHeapSize()==0){
           txtMeja2.setText("");
           //tambahkan modal dialog 
           System.out.println("ANTRIAN KOSONG");
           
           JOptionPane.showMessageDialog(rootPane, "ANTRIAN KOSONG");
            
        }else {
            kode = heap.getMin(); 
            txtMeja2.setText(kode);
            URL fileurut = formUtama.class.getResource("sound/nomor-urut.wav");
            
            PlaySound(fileurut);
            
            char[] putar =kode.toCharArray();
            int i = 0;
            
            for (i=0;i<putar.length;i++) {
              
                    PlaySound(formUtama.class.getResource("sound/"+putar[i]+".wav"));  
                
            }
            
            /*
            while(i<putar.length){
                try{
                    URL file = formUtama.class.getResource("assets/"+putar[i]+".wav");
                    PlaySound(file);
                    i++;
                }catch(Exception e){
                   e.printStackTrace();
                }
            
            }
            */
            
           URL kemeja = formUtama.class.getResource("sound/loket.wav");
           PlaySound(kemeja);
           
           URL dua2 = formUtama.class.getResource("sound/2.wav");
           PlaySound(dua2);
        }
    }//GEN-LAST:event_btnMeja2ActionPerformed
    
    
    private static void PlaySound(URL sound){
     try{
         AudioClip clip = Applet.newAudioClip(sound);
         clip.play();
         File sndFile = new File(sound.getFile());
         Thread.sleep(1000);
     }   
     catch(Exception e){
         e.printStackTrace();
     }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBisnis;
    private javax.swing.JButton btnMeja2;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtMeja1;
    private javax.swing.JTextField txtMeja2;
    // End of variables declaration//GEN-END:variables
}
